### ISSUE TITLE
Action to trigger data saving mode

### ISSUE THREAD

**Issue by terrorist96** [JayT5/ChromePie#16]
I use AdAway and sometimes it can break a video or not load a page because it conflicts with the filters. Enabling data saving mode is a fast workaround to get the page to load. Can enabling/disabling data saving mode be added as a trigger?
Regards 

(Just want to consolidate my other posts here)
Suppress pie controls from being triggered when typing in the URL bar?
Suppress pie controls from being triggered if there is already a touch input on the screen (to prevent, when scrolling with your thumb, your [thenar eminence](https://2.bp.blogspot.com/_I8t0EbwStUE/TF7q4P8NpfI/AAAAAAAAAhw/tNykB0ULzjc/s1600/thenar.GIF.gif) from triggering pie controls).

**Comment by JayT5** [comment]
Added: 2c4215e, 4bf4715 & 75e451c. Preventing the menu from being triggered when there is already a touch input isn't perfect as it only works when you are scrolling, not just pressing the screen but it's better than it was. Trying to figure out touch handling in Chrome was difficult so this was the best I could do...
Thanks for the suggestions!

**Comment by terrorist96** [comment]
You're awesome! Awaiting the new version in the repo. :smiley:
