### ISSUE TITLE
Xposed error log when closing a tab

### ISSUE THREAD

**Issue by terrorist96** [JayT5/ChromePie#17]
01-02 05:14:16.422 E/Xposed  ( 8030): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
01-02 05:14:16.422 E/Xposed  ( 8030): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:949)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at com.jt5.xposed.chromepie.Utils.callMethod(Utils.java:86)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at com.jt5.xposed.chromepie.Controller.getUrl(Controller.java:289)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at com.jt5.xposed.chromepie.Controller.isDistilledPage(Controller.java:604)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at com.jt5.xposed.chromepie.PieControl$4.afterHookedMethod(PieControl.java:307)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:689)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at org.chromium.content_public.browser.WebContentsObserver.didNavigateMainFrame(<Xposed>)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at org.chromium.content.browser.webcontents.WebContentsObserverProxy.didNavigateMainFrame(WebContentsObserverProxy.java:109)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:37)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at android.os.Looper.loop(Looper.java:148)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at java.lang.reflect.Method.invoke(Native Method)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-02 05:14:16.422 E/Xposed  ( 8030): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)
01-02 05:14:16.423 E/Xposed  ( 8030): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
01-02 05:14:16.423 E/Xposed  ( 8030): 	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:949)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at com.jt5.xposed.chromepie.Utils.callMethod(Utils.java:86)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at com.jt5.xposed.chromepie.Controller.getUrl(Controller.java:289)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at com.jt5.xposed.chromepie.Controller.isDistilledPage(Controller.java:604)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at com.jt5.xposed.chromepie.PieControl$4.afterHookedMethod(PieControl.java:307)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:689)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at org.chromium.content_public.browser.WebContentsObserver.didNavigateMainFrame(<Xposed>)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at org.chromium.content.browser.webcontents.WebContentsObserverProxy.didNavigateMainFrame(WebContentsObserverProxy.java:109)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:37)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at android.os.Looper.loop(Looper.java:148)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at java.lang.reflect.Method.invoke(Native Method)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-02 05:14:16.423 E/Xposed  ( 8030): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:114)

**Comment by terrorist96** [comment]
I don't have these errors anymore after rebooting. But it might come back when I don't reboot for awhile

**Comment by JayT5** [comment]
Thanks for reporting, possibly fixed in 38b0a00. I'm not exactly sure why this happened, but the code that caused this is to do with toolbar colouring which will (eventually) be removed once this feature has been added to Chrome stable. This seems to be a very rare crash and you were just unlucky with the timing of the tab closure if it was navigating to a different page at the same time or something.
