### ISSUE TITLE
Add a setting for manual pie-item icon size

### ISSUE THREAD

**Issue by jarmst** [JayT5/ChromePie#18]
Setup first: I'm using an HTC One M8, and after installing I noticed the radial menu icons were larger than I prefer. The AOSP quick-controls feature looks like this ([screenshot here](http://i.imgur.com/dv1uj5k.png)), and I'm guessing that's how the module is supposed to scale the icons.

I went ahead and repackaged a quick-n-dirty solution: replaced all icon images with the 'm' size icons. The result is almost perfect parity with AOSP ([screenshot of modified ChromePie](http://i.imgur.com/JYYsWAR.png)).

And here's the feature request: add a setting to manually select the icon size, with the default of 'auto.' I haven't dug much through the source, but I might try to add it myself some time this week.

**Comment by JayT5** [comment]
Nope, the icons (for me at least) are scaled to the correct size (bigger than how they appear in your screenshots), and match the sizes in the AOSP browser. Check out this video (sorry I can't provide any screenshots): https://youtu.be/GfUe6DJfKLQ?t=13s. Is that the size they were for you? Were you using the AOSP browser with a modified screen density or something? Also bear in mind that the icons don't scale if you change the size of the menu in the settings, so they may appear too small/large for that reason.

**Comment by jarmst** [comment]
[Here's what the icon size looks like in the latest version.](http://i.imgur.com/oWOtX6U.png). I believe the original AOSP sizes may have been closer to that, but an update within the last year or so made them smaller (which I ended up preferring).

Not using any modified resolution/density, the first image in my original comment is what the latest update of the AOSP looks like on my phone.

**Comment by JayT5** [comment]
Okay, I see. I didn't think that the AOSP browser was still being maintained, where are you getting it from?

But while I probably won't add this myself feel free to open a pull request and I can merge it :)

**Comment by jarmst** [comment]
I believe HTC is updating it under HTC Internet, last update Dec 2015. I didn't realize the lab updates were so HTC-specific!

I may get a chance to do it this weekend (hopefully) but we'll see.

**Comment by JayT5** [comment]
Ah right, that makes sense. Yeah must be, there doesn't appear to be any commits to the [AOSP browser](https://github.com/android/platform_packages_apps_browser/commits/master) for the last 9 months.

Cool, no worries. Let me know if you have any problems.
