### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by Freewander10** [JayT5/ChromePie#28]
On the latest versions of Chrome Dev, some of the actions are no longer working.

**Comment by JayT5** [comment]
Yeah some of the method names in Chrome have random characters added to the end meaning they're not being called, you can see what I mean here: http://i.imgur.com/Wg3h027.png 
I'll try and fix it soon.

**Comment by Freewander10** [comment]
Yea. I see them. 
Thanks 👍

**Comment by montupatel101** [comment]
Any Solution so far?
I used to love full screen browsing on Chrome but seems like is not working anymore.

**Comment by JayT5** [comment]
> I'll try and fix it soon.

3 months later... 🙈
Fixed here 918ad8c
