### ISSUE TITLE
Pyrope

### ISSUE THREAD

**Issue by manuw2009** [JayT5/ChromePie#29]
Hi,
any plan to support Pyrope browser, which is based on Chromium ?
that would be great

**Comment by Jisxu** [comment]
if possible,you can add the package name of the brower in right place in the code. The code detectes the package name to determine wether support the brower

**Comment by manuw2009** [comment]
I believe the package name is :com.ninnix96.pyrope.browser
Any way to do this without recompiling ?

**Comment by Jisxu** [comment]
maybe you can use some xposed app to change the brower's package name to anything in the code,such as chromium╮（╯＿╰）╭
recompiling it won't take too much time

**Comment by JayT5** [comment]
I've had a look and I'm afraid I don't think it'll be compatible. Although
it uses Chromium libs, the UI is based on Gello which isn't supported.

**Comment by Jisxu** [comment]
Got it.BTW,when would you fix some unworking actions such as  'show tabs' on chroium and chrome 54.I'm looking forword for it.

**Comment by JayT5** [comment]
I've added this: ddd3dcc, so if any newly installed browsers are supported they'll be added automatically
