### ISSUE TITLE
Adding support for chrome's fork?

### ISSUE THREAD

**Issue by byaka** [JayT5/ChromePie#37]
Hey m8, ty for this awesome extension. Dont know why google don't add this feature to chrome - i'm use it 5 years from old 4.0.* android's browser.
anyway, can u add support for chrome fork [bromite](https://www.bromite.org/)? as i'm understand it don't have any special difference, that need additional work for you.

**Comment by JayT5** [comment]
Should already be working dude, at least it is for me on v68.0.3440.110.

**Comment by byaka** [comment]
hm, it's strange. i have both chrome and bromite installed - pie works in first but not in second.
android 4.1, wexler tab 7t, chrome 62 (lates chrome have problems on my tablet), latest bromite, latest chromePie.

**Comment by JayT5** [comment]
Yeah that's weird. And you're definitely on the latest module version (0.7.4)? There were issues to do with obfuscation on Chrome versions 67+ which have since been fixed in the latest versions, sounds like it could be related to that. Any logs in the Xposed logs?
